"""Update Payment model

Revision ID: 154916ae017a
Revises: 92251b92c20b
Create Date: 2023-09-08 15:14:27.626501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154916ae017a'
down_revision = '92251b92c20b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orderNumber', sa.String(length=50), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.drop_column('orderNumber')

    # ### end Alembic commands ###
